const fs = require('fs');
const path = require('path');
const crypto = require('crypto');

function walk(dir) {
  let results = [];
  if (!fs.existsSync(dir)) return results;
  const list = fs.readdirSync(dir);
  list.forEach(file => {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);
    if (stat && stat.isDirectory()) {
      results = results.concat(walk(fullPath));
    } else {
      // Exclude build_hash.ts to avoid circular hashing
      if (!file.endsWith('build_hash.ts') && !file.endsWith('build_hash.js')) {
        results.push(fullPath);
      }
    }
  });
  return results;
}

function generateHash() {
  const backendSrc = path.join(__dirname, '..', 'backend', 'src');
  const extensionSrc = path.join(__dirname, '..', 'extension', 'src');

  const files = [
    ...walk(backendSrc),
    ...walk(extensionSrc)
  ].sort(); // Sort to ensure deterministic order

  const hasher = crypto.createHash('sha256');

  files.forEach(file => {
    const relativePath = path.relative(path.join(__dirname, '..'), file);
    hasher.update(relativePath); // Include file path
    const content = fs.readFileSync(file);
    hasher.update(content); // Include file content
  });

  const hash = hasher.digest('hex');
  console.log(`Generated build hash: ${hash}`);

  const content = `// This file is auto-generated by scripts/generate-hash.js. Do not edit.
export const BUILD_HASH = '${hash}';
`;

  // Ensure directories exist
  if (!fs.existsSync(backendSrc)) {
    fs.mkdirSync(backendSrc, { recursive: true });
  }
  if (!fs.existsSync(extensionSrc)) {
    fs.mkdirSync(extensionSrc, { recursive: true });
  }

  fs.writeFileSync(path.join(backendSrc, 'build_hash.ts'), content);
  fs.writeFileSync(path.join(extensionSrc, 'build_hash.ts'), content);
  console.log('Successfully wrote build_hash.ts to backend/src/ and extension/src/');
}

generateHash();
